### PR TITLE
changed length parameter to a scale parameter

### PR DESCRIPTION
**Pull request by dpaiton**
scale parameter is easier to think about than pixel length

### CODE REVIEW

**Comment by dpaiton** [comment]
Should I leave this a separate branch?

**Comment by fzliu** [comment]
Main reason I changed it to max length is so that we can track the input size better. If we define a fixed scale factor, a 1920x1080 image will be scaled to the same size as a 640x360 one. I'm running some tests trying different fixed length style versus content images, and this makes it a bit easier to do so. I think we might eventually want to change back and/or have both, so let's keep the PR open for now but hold off on merging it.

**Comment by dpaiton** [comment]
I agree, although I'm not sure what you mean when you say that a 1920x1080 image will be scaled to the same as a 640x360 one. My original implementation scaled both the content and the style image to scale_factor \* content_size. This way the output size is also scale_factor \* content_size. It was just much easier for me to think "I want to be N% of the original size" than to think in terms of pixel length.

Maybe we should just allow either specification, and force one to take priority if both are specified?

**Comment by dpaiton** [comment]
Oh, also, this pull request here does not follow my original implementation. Now both the content & style image are scaled by scale_factor. The rest of the code behaves like your length code did.

**Comment by dpaiton** [comment]
The more I think about it the more I understand now what you were getting at. I agree that length is a better parameter. For a demo you'd want to have a fixed length to display the images so you can be sure of the wait time, and if you're saving multiple sizes you would expect them to follow certain

**Comment by dpaiton** [comment]
Sorry - bad at GIThub. I can see a reason for both parameters both for prototyping and for the demo. For now I'm fine with working with length as a specifier. We can discuss it more in the future.

**Comment by fzliu** [comment]
Yeah I was experimenting with changing the size of the style image, so that stuff will be different. Didn't know what your timeline was for continuing to work on the code (but I know now, so I'll hold off on doing experimentation in master).

One more thing - the style and content gradients are now normalized via `grad /= np.nextafter(np.abs(grad).sum(), INF)`, so watch out for different results. I think this, combined with using the full set of features from each layer, is giving decent-ish results for googlenet. Still not as good as vgg though.

**Comment by fzliu** [comment]
Actually I'm just not going to merge anything into master for the time being.

**Comment by dpaiton** [comment]
Yeah I'm still actively working on it. I haven't pushed anything because I haven't had access to my VPN since I left the office.

**Comment by dpaiton** [comment]
I'm going to close this pull request and delete the branch. It is an easy feature to add later and for now isn't necessary.

**Pull request closed without merging**
